### ISSUE TITLE
species-specific group size estimation

### ISSUE THREAD

**Issue by amandalbradford** [smwoodman/swfscDAS#9]
Aloha @smwoodman - After finding some species-specific group sizes (GsSpBestx) being higher than the total group sizes (GsSchoolBest), @mchill808 and I realized that swfscDAS is averaging observer best estimates for GsSchoolBest as expected. However, for computing GsSpBestx for mixed-species sightings, instead of 1) averaging the observer best estimates, then 2) averaging the available percentages, and finally 3) multiplying those average values for each species (as we have always done for the group sizes that feed into abundance estimation), we found that swfscDAS is 1) multiplying each observer's GsSchoolBest by their GsSpBestx and then 2) averaging those values together for the final GsSpBestx, even though the included GsSchoolBest and SpPercx represent the averaged values that we think should be multiplied instead.

If all observers provide percentages along with their estimates, then the two approaches above are more consistent (but still differ). However, the discrepancy becomes greater with fewer estimates associated with percentages, with some species-specific group sizes even ending up higher than the total group size estimate. I know you provide the complete format to allow for differences in group size estimation, but we wondered if you would consider revising the current species-specific group size estimation approach in swfscDAS? Thank you!

**Comment by smwoodman** [comment]
In short, I don't remember a specific reason for the current approach, and I am happy to update `das_sight` as you propose. I agree with y'all that `sum(GsSpBestx)` should equal `GsSchoolBest`, and same for the Highs and Lows, and imagine that I just didn't notice this potential discrepancy because the files that I was using for testing had sightings where all observers provided percentages.
